school-database/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^school/', include('school.urls')),
    url(r'^admin/', admin.site.urls),
]

school/urls.py
from django.conf.urls import url

from . import views


app_name = 'school'
urlpatterns = [
    url(r'^$', views.display_teachers, name='teachers'),
    url(r'teacher/(?P<teacher_id>[0-9]+)', views.get_teacher_info, name='teacher'),
    url(r'add/', views.add, name='add'),
    url(r'delete/(?P<teacher_id>[0-9]+)', views.delete, name='delete'),
    url(r'update/(?P<teacher_id>[0-9]+)', views.update, name='update'),
]

school/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    patronymic = models.CharField(max_length=30)


class SchoolClass(models.Model):
    teacher = models.OneToOneField(Teacher, models.CASCADE, default=1)
    number = models.IntegerField()
    letter = models.CharField(max_length=1, default='a')


class Subject(models.Model):
    name = models.CharField(max_length=30)
    teacher = models.OneToOneField(Teacher, models.CASCADE, default=1)


class Pupil(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    patronymic = models.CharField(max_length=30)
    school_class = models.ForeignKey(SchoolClass, models.CASCADE, default=1)


class Achievement(models.Model):
    BAD = '2'
    UNSATISFACTORY = '3'
    GOOD = '4'
    EXCELLENT = '5'

    subject = models.ForeignKey(Subject, models.CASCADE, default=1)
    pupil = models.ForeignKey(Pupil, models.CASCADE, default=1)
    MARK = (
        (BAD, '2'),
        (UNSATISFACTORY, '3'),
        (GOOD, '4'),
        (EXCELLENT, '5'))
    mark = models.CharField(max_length=15,
                            choices=MARK,
                            default=BAD)

school/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Teacher


def get_values(src_dict, *keys):
    return (src_dict[key] for key in keys)


def display_teachers(request):
    teacher_list = Teacher.objects.order_by('id')
    return render(request,
                  'school/teachers.html',
                  {'teacher_list': teacher_list})


def get_teacher_info(request, teacher_id):
    return render(request,
                  'school/teacher.html',
                  {"teacher": get_object_or_404(Teacher, pk=teacher_id)})


def add(request):
    # first_name, last_name, patronymic = (request.POST[key] for key in ['first_name', 'last_name', 'patronymic'])
    first_name, last_name, patronymic = get_values(request.POST, 'first_name', 'last_name', 'patronymic')
    if first_name and last_name and patronymic:
        new_teacher = Teacher(first_name=first_name,
                              last_name=last_name,
                              patronymic=patronymic)
        new_teacher.save()

    return redirect('school:teachers')


def delete(request, teacher_id):
    get_object_or_404(Teacher, pk=teacher_id).delete()
    return redirect('school:teachers')


def update(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)
    first_name, last_name, patronymic = get_values(request.GET, 'first_name', 'last_name', 'patronymic')
    if first_name and last_name and patronymic:
        teacher.last_name = last_name
        teacher.first_name = first_name
        teacher.patronymic = patronymic
        teacher.save()

    return redirect('school:teachers')

templates/school/teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher's data</title>
</head>
<body>
<form action="{% url 'school:update' teacher.id %}" method="update">
    {% csrf_token %}
    <p>Enter new data: </p>
    <p>Teacher's new first name: </p>
    <input type="text" name="first_name" value="{{ teacher.first_name }}">
    <p>Teacher's new last name: </p>
    <input type="text" name="last_name" value="{{ teacher.last_name }}">
    <p>Teacher's new patronymic: </p>
    <input type="text" name="patronymic" value="{{ teacher.patronymic }}">
    <input type="submit" value="Update">
</form>
</body>
</html>

templates/school/teachers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher list</title>
</head>
<body>
<h1>Teacher list</h1>
{% if teacher_list %}
    {#    <ul>#}
    {#        {% for teacher in teacher_list %}#}
    {#            <li><a href="teacher/{{ teacher.id }}/">{{ teacher.last_name }}</a></li>#}
    {#        {% endfor %}#}
    {#    </ul>#}
    <table>
        <tr>
            <th>#</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Patronymic</th>
            <th></th>
        </tr>
        {% for teacher in teacher_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.patronymic }}</td>
                <td><a href="{% url 'school:delete' teacher.id %}">Delete</a></td>
                <td><a href="{% url 'school:teacher' teacher.id %}">Update</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>None</p>
{% endif %}
<form action="{% url 'school:add' %}" method="post">
    {% csrf_token %}
    <p>Enter your data: </p>
    <p>Teacher's first name: </p>
    <input type="text" name="first_name">
    <p>Teacher's last name: </p>
    <input type="text" name="last_name">
    <p>Teacher's patronymic: </p>
    <input type="text" name="patronymic">
    <input type="submit" value="Add">
</form>
</body>
</html>